es01:
  image: elasticsearch:2.3
  ports:
    - "9200:9200"
    - "9300:9300"
es02:
  image: elasticsearch:2.3
  links:
   - es01:elasticsearch

es03:
  image: elasticsearch:2.3
  links:
   - es01:elasticsearch
   - es02:es02

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/*.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/patterns:/etc/logstash/patterns
  ports:
    - "5400:5400"
  links:
    - es01:elasticsearch

kibana:
  build: ./kibana
  volumes:
    - ./kibana/config:/opt/kibana/config
  ports:
    - "5601:5601"
  links:
    - es01:elasticsearch
#curl -XPUT "http://0.0.0.0:9200/.kibana/_settings" -d '{ "index" : { "max_result_window" : 2147483647 } }'
